### ISSUE TITLE
Running on Xampp

### ISSUE THREAD

**Issue by dannyx93** [eau-claire-energy-cooperative/simple-inventory#18]
Is it possible to run the script on Windows Server or via XAMPP server?

**Comment by robweber** [comment]
I imagine XAMPP would work. As long as Apache, PHP, and MySQL (MariaDB) are available there isn't any reason it wouldn't work. Might be some additional tinkering in case the right Apache modules aren't enabled by default (mod_rewrite in particular).

**Comment by dannyx93** [comment]
Could you have a simple instruction on how to install on Xampp: where is the sql database structure. e.t.c

**Comment by robweber** [comment]
Been thinking about this one and I really don't have any instructions for the XAMPP system. I'm not familiar with it and don't really have a need to stand one up. I imagine you can adapt the Linux instructions however that's what this is designed to work with.
