### ISSUE TITLE
Extend Checkout - Enhancement

### ISSUE THREAD

**Issue by jporter0731** [eau-claire-energy-cooperative/simple-inventory#24]
Would be nice to be able to extend the checkout period for a user in the situation that a checkout needs to be extended for one reason or another.

**Comment by robweber** [comment]
Was looking in to this more. Updating any date on an existing reservation may impact other reservations where devices are already assigned (if the same device is in play). Just updating the date in the DB may conflict with downstream requests. A proposed order of operations for this could be: 

1. Set new date (either start or end)
2. Pull in existing reservation info
3. Using [this function](https://github.com/eau-claire-energy-cooperative/simple-inventory/blob/master/www/app/Controller/CheckoutController.php#L309) pass in the new check in dates to compare existing reservations
4. If passing (no conflicts) set the new date
5. If not passing (conflict) return error with info on conflicting reservation (dates of reservation overlap). 

When conflicts happen an admin may have to adjust one or more other reservations (assuming that can be done) to accommodate a change. In some cases the reservation may not be able to be extended - and that is OK given the constraints of the dates and number of devices.
